#!/bin/sh

mkdir -p opk
cp ./sms_sdl opk/sms_sdl
cp ./sms_sdl.png opk/icon.png
cp ./docs/license opk/COPYING

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=SMS Plus GX
Comment=SMS/GG/SG emulator
Exec=sms_sdl %f
Icon=icon
Terminal=false
Type=Application
Categories=emulators;
X-OD-NeedsDownscaling=false' > opk/default.gcw0.desktop

mksquashfs ./opk smsplus_rs90.opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
